baseURL = "https://weilumeng.github.io/"
locale = "en-US"
title = "Weilu Meng"
theme = "hugo-ht"
footnotereturnlinkcontents = "↩"
enableRobotsTXT = true

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.en]]
    name = "Research"
    url = "/research/"
    weight = 2

[[menu.en]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3

[[menu.en]]
    name = "Conferences"
    url = "/conferences/"
    weight = 4



[params]
    description = "Personal academic website of Weilu Meng"

    GithubEdit = "https://github.com/weilumeng/weilumeng.github.io/edit/main/content/"

    copyrightYear = "2022-2026"

    GithubRepo = "https://github.com/weilumeng/weilumeng.github.io"

    ContentSource = "https://raw.githubusercontent.com/weilumeng/weilumeng.github.io/main/content/"

[params.logo]

  # Change the logo picture as your prefer:

  url = "image/Vicky.jpg"
  width = 50.0
  height = 50.0
  alt = "Weilu-Meng"

[params.lang]

    [params.lang.author]
      en = "Weilu Meng"
      cn = "鹿吉路"
    
    [params.lang.madeWith]
      en = "Made with"
      cn = "本站驱动"
    
    [params.lang.edit]
      en = "Suggest an edit of this page"
      cn = "编辑本页"
    
    [params.lang.lastupdate]
      en = "Last modified on"
      cn = "最后一次修改于"
    
    [params.lang.Sitelastupdate]
      en = "Site last updated on"
      cn = "最近一次更新于"
    
    [params.lang.sourceCode]
      en = "Content in"
      cn = "内容存于"
    
    [params.lang.subscribe]
      en = "Subscribe"
      cn = "订阅"
    
    [params.lang.license]
      en = "License"
      cn = "版权"

[markup]
 defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = true
    
    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
    
    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

[imaging]
quality = 100
